on:
  push:
    branches: main
  workflow_dispatch:
name: Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    
    - name: Minify JSON
      uses: StefanEnsmann/Minify-JSON-Action@1.1.0
      with:
        input_file: input.json
        output_file: output.json
    
    - name: Push
      run: |
          date > generated.txt
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push
